name: Deploy to ECR

on:
    workflow_dispatch:
    push:
      branches:
        - main  # replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 
      with:
        role-to-assume: arn:aws:iam::550761455669:role/github-deploy-admin-role
        aws-region: us-east-2

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: Configure Docker to use AWS ECR registry
    #   run: | 
    #     echo "{\"credsStore\": \"ecr-login\"}" > $HOME/.docker/config.json
    
    # - name: Configure AWS CLI
    #   run: |
    #     aws configure set aws_access_key_id value ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws configure set aws_secret_access_key value ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws configure set region value ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: vod-portal-ecr-image
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG